# Generated by Django 2.2 on 2019-05-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcs', '0017_auto_20190428_0711'),
        ('django_celery_beat', '0011_fix_migration_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='func',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tasks', to='funcs.Func'),
        ),
    ]
