# Generated by Django 2.2 on 2019-05-04 12:19

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='name',
            field=models.CharField(help_text='Short Description For This Task', max_length=200, verbose_name='Name'),
        ),
    ]
