# Generated by Django 2.2.8 on 2019-12-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0013_auto_20190504_1219'),
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
    ]

    operations = [
    ]
